package service

import (
	"context"
	"fmt"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	infradb "github.com/insmtx/Leros/backend/internal/infra/db"
	skilltoken "github.com/insmtx/Leros/backend/internal/skill"
	"github.com/insmtx/Leros/backend/types"
	"github.com/ygpkg/yg-go/logs"
)

// invokedSkillActivityRecorder writes the project activity generated by an
// automatic Skill association. It is intentionally separate from the public
// project-plugin API so message delivery can keep its best-effort semantics.
type invokedSkillActivityRecorder func(
	ctx context.Context,
	tx *gorm.DB,
	caller *types.Caller,
	projectPublicID string,
	action types.ProjectActivityAction,
	payload types.ProjectActivityPayload,
) error

type invokedSkillBindingFailure struct {
	Code  string
	Stage string
	Err   error
}

type invokedSkillBindingResult struct {
	Added        []string
	AlreadyBound []string
	System       []string
	Failures     []invokedSkillBindingFailure
}

type invokedSkillBindingOutcome uint8

const (
	invokedSkillOutcomeAlreadyBound invokedSkillBindingOutcome = iota
	invokedSkillOutcomeAdded
	invokedSkillOutcomeSystem
)

// bindInvokedSkillsToProject associates invoked Skills with a project before
// its Worker snapshot is built. Codes come from <skill-chip data-code> in content.
// Each code is isolated in its own transaction so an unavailable Skill does
// not block message delivery or the association of other valid Skills.
func bindInvokedSkillsToProject(
	ctx context.Context,
	database *gorm.DB,
	project *types.Project,
	caller *types.Caller,
	content string,
	record invokedSkillActivityRecorder,
) invokedSkillBindingResult {
	result := invokedSkillBindingResult{}
	if database == nil || project == nil || caller == nil {
		return result
	}

	seen := make(map[string]struct{})
	for _, rawCode := range skilltoken.ParseTokensOnly(content) {
		code := strings.TrimSpace(rawCode)
		if code == "" {
			continue
		}
		key := strings.ToLower(code)
		if _, exists := seen[key]; exists {
			continue
		}
		seen[key] = struct{}{}

		outcome, err := bindInvokedSkill(
			ctx,
			database,
			project,
			caller,
			code,
			record,
		)
		if err != nil {
			result.Failures = append(result.Failures, invokedSkillBindingFailure{
				Code:  code,
				Stage: invokedSkillFailureStage(err),
				Err:   err,
			})
			continue
		}
		switch outcome {
		case invokedSkillOutcomeAdded:
			result.Added = append(result.Added, code)
		case invokedSkillOutcomeAlreadyBound:
			result.AlreadyBound = append(result.AlreadyBound, code)
		case invokedSkillOutcomeSystem:
			result.System = append(result.System, code)
		}
	}

	return result
}

// bindInvokedSkill resolves one Skill and binds it to the project. The
// in-process install lock covers the marketplace-install plus binding pair so
// concurrent messages cannot create competing organization revisions.
func bindInvokedSkill(
	ctx context.Context,
	database *gorm.DB,
	project *types.Project,
	caller *types.Caller,
	code string,
	record invokedSkillActivityRecorder,
) (invokedSkillBindingOutcome, error) {
	unlock := lockSkillAutoInstall(caller.OrgID, code)
	defer unlock()

	var outcome invokedSkillBindingOutcome
	err := database.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		systemPlugin, err := infradb.GetSystemPluginByCode(ctx, tx, "skill", code)
		if err != nil {
			return fmt.Errorf("resolve system Skill: %w", err)
		}
		if systemPlugin != nil &&
			systemPlugin.Origin == builtinWorkerOrigin &&
			systemPlugin.Status == types.PluginStatusActive &&
			systemPlugin.CurrentRevision > 0 {
			outcome = invokedSkillOutcomeSystem
			return nil
		}

		organizationPlugin, err := getOrganizationSkillByCode(ctx, tx, caller.OrgID, code)
		if err != nil {
			return fmt.Errorf("resolve organization Skill: %w", err)
		}
		if organizationPlugin != nil {
			if organizationPlugin.Status != types.PluginStatusActive {
				return fmt.Errorf("organization Skill is not active (status=%s)", organizationPlugin.Status)
			}
			added, err := ensureInvokedSkillBinding(ctx, tx, project, caller, organizationPlugin, record)
			if err != nil {
				return err
			}
			if added {
				outcome = invokedSkillOutcomeAdded
			} else {
				outcome = invokedSkillOutcomeAlreadyBound
			}
			return nil
		}

		release, err := loadPublishedMarketplaceReleaseByIdentity(ctx, tx, "skill", code)
		if err != nil {
			return fmt.Errorf("resolve marketplace Skill: %w", err)
		}
		if release == nil || release.Item == nil {
			return fmt.Errorf("Skill %q is not available in the organization or marketplace", code)
		}
		_, sourceRevision, sourceContent, err := loadMarketplaceSource(ctx, tx, release.Item, true)
		if err != nil {
			return fmt.Errorf("load marketplace Skill source: %w", err)
		}
		plugin, _, err := (&pluginService{db: database}).installMarketplaceSkillIntoOrg(
			ctx,
			tx,
			caller.OrgID,
			"user",
			caller.Uin,
			release.Item,
			sourceRevision,
			sourceContent,
			false,
		)
		if err != nil {
			return fmt.Errorf("install marketplace Skill: %w", err)
		}
		if plugin == nil || plugin.Status != types.PluginStatusActive {
			return fmt.Errorf("installed marketplace Skill is not active")
		}
		added, err := ensureInvokedSkillBinding(ctx, tx, project, caller, plugin, record)
		if err != nil {
			return err
		}
		if added {
			outcome = invokedSkillOutcomeAdded
		} else {
			outcome = invokedSkillOutcomeAlreadyBound
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return outcome, nil
}

func getOrganizationSkillByCode(
	ctx context.Context,
	database *gorm.DB,
	orgID uint,
	code string,
) (*types.Plugin, error) {
	var plugin types.Plugin
	err := database.WithContext(ctx).
		Where(
			"owner_scope = ? AND org_id = ? AND kind = ? AND code = ?",
			types.OwnerScopeOrganization,
			orgID,
			"skill",
			code,
		).
		First(&plugin).Error
	if err == gorm.ErrRecordNotFound {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &plugin, nil
}

func ensureInvokedSkillBinding(
	ctx context.Context,
	database *gorm.DB,
	project *types.Project,
	caller *types.Caller,
	plugin *types.Plugin,
	record invokedSkillActivityRecorder,
) (bool, error) {
	existing, err := infradb.ListProjectPlugins(ctx, database, caller.OrgID, project.ID, "skill")
	if err != nil {
		return false, fmt.Errorf("list project Skills: %w", err)
	}
	for _, existingPlugin := range existing {
		if existingPlugin.ID == plugin.ID {
			return false, nil
		}
	}

	binding := &types.ProjectPluginBinding{
		ProjectID: project.ID,
		PluginID:  plugin.ID,
		Enabled:   true,
		Config:    []byte(`{}`),
		CreatedBy: caller.Uin,
		UpdatedBy: caller.Uin,
	}
	insert := database.WithContext(ctx).
		Clauses(clause.OnConflict{DoNothing: true}).
		Create(binding)
	if insert.Error != nil {
		return false, fmt.Errorf("create project Skill binding: %w", insert.Error)
	}
	if insert.RowsAffected == 0 {
		return false, nil
	}

	if record != nil {
		action, payload := projectPluginActivity(plugin, true)
		if err := record(ctx, database, caller, project.PublicID, action, payload); err != nil {
			return false, fmt.Errorf("record Skill binding activity: %w", err)
		}
	}
	return true, nil
}

func invokedSkillFailureStage(err error) string {
	message := strings.ToLower(err.Error())
	switch {
	case strings.Contains(message, "marketplace"):
		return "marketplace"
	case strings.Contains(message, "binding") || strings.Contains(message, "project"):
		return "binding"
	case strings.Contains(message, "organization") || strings.Contains(message, "system"):
		return "resolve"
	default:
		return "unknown"
	}
}

func logInvokedSkillBindingResult(ctx context.Context, project *types.Project, result invokedSkillBindingResult) {
	if project == nil {
		return
	}
	if len(result.Added) == 0 && len(result.Failures) == 0 {
		return
	}
	failed := make([]string, 0, len(result.Failures))
	for _, failure := range result.Failures {
		failed = append(failed, fmt.Sprintf("%s[%s]: %v", failure.Code, failure.Stage, failure.Err))
	}
	if len(result.Failures) > 0 {
		logs.WarnContextf(
			ctx,
			"auto-associate invoked Skills: project=%s added=%v failed=%v",
			project.PublicID,
			result.Added,
			failed,
		)
		return
	}
	logs.InfoContextf(ctx, "auto-associate invoked Skills: project=%s added=%v", project.PublicID, result.Added)
}
