package accounterror

import "errors"

var (
	ErrDatabaseRequired           = errors.New("数据库不可用")
	ErrAccountRequired            = errors.New("请输入账号")
	ErrInvalidAccountOrPassword   = errors.New("账号或密码错误")
	ErrEmailRequired              = errors.New("请输入邮箱")
	ErrInvalidEmailFormat         = errors.New("请输入正确的邮箱")
	ErrPasswordRequired           = errors.New("请输入密码")
	ErrPasswordsDoNotMatch        = errors.New("密码不一致")
	ErrPasswordTooShort           = errors.New("密码长度不能少于8位")
	ErrPasswordTooLong            = errors.New("密码长度不能超过20位")
	ErrPasswordContainsChinese    = errors.New("密码不能包含中文")
	ErrPasswordContainsWhitespace = errors.New("密码不能包含空格")
	ErrPasswordStrength           = errors.New("密码需数字/大小写字母/字符至少3种")
	ErrEmailAlreadyExists         = errors.New("该邮箱已注册")
	ErrPhoneAlreadyExists         = errors.New("该手机号已注册")
	ErrInvalidEmailOrPassword     = errors.New("邮箱或密码错误")
	ErrLoginAttemptsExceeded      = errors.New("登录失败次数过多，请稍后再试")
	ErrPhoneRequired              = errors.New("请输入手机号")
	ErrPhoneOrEmailRequired       = errors.New("手机号或邮箱至少填写一个")
	ErrInvalidPhoneFormat         = errors.New("请输入正确的手机号")
	ErrPhoneCodeRequired          = errors.New("请输入验证码")
	ErrInvalidPhoneCode           = errors.New("验证码错误或已过期")
	ErrPhoneCodeSendTooOften      = errors.New("验证码发送太频繁，请稍后再试")
	ErrSMSDeliveryFailed          = errors.New("验证码发送失败，请稍后再试")
	ErrRefreshTokenRequired       = errors.New("刷新令牌不能为空")
	ErrRefreshTokenInvalid        = errors.New("登录已过期，请重新登录")
	ErrUserNotFound               = errors.New("用户不存在")
	ErrUserOrgNotFound            = errors.New("用户组织信息不存在")
	ErrUserOrgNotAllowed          = errors.New("用户未加入该组织")
	ErrLoginRequired              = errors.New("请先登录")
	ErrOrgNotFound                = errors.New("组织不存在")
	ErrOrgIDRequired              = errors.New("组织ID不能为空")
	ErrNeedCreateCompany          = errors.New("请先创建或加入组织")
	ErrJWTSecretRequired          = errors.New("登录配置缺失")
	ErrOrganizationLimitExceeded  = errors.New("最多只能加入三个组织")
	ErrPermissionDenied           = errors.New("无权操作")

	ErrWorkerBootstrapTokenInvalid = errors.New("invalid worker bootstrap token")
	ErrWorkerNotFound              = errors.New("worker not found")
	ErrWorkerOrgMismatch           = errors.New("worker organization mismatch")
	ErrWorkerNotActive             = errors.New("worker is not active")

	ErrInvalidArg            = errors.New("参数无效")
	ErrNotImplementedEdition = errors.New("当前版本不支持此特性")
)
