package accounterror

import "errors"

var (
	ErrDatabaseRequired           = errors.New("account: 数据库不可用")
	ErrEmailRequired              = errors.New("account: 请输入邮箱")
	ErrInvalidEmailFormat         = errors.New("account: 请输入正确的邮箱")
	ErrPasswordRequired           = errors.New("account: 请输入密码")
	ErrPasswordsDoNotMatch        = errors.New("account: 密码不一致")
	ErrPasswordTooShort           = errors.New("account: 密码长度不能少于8位")
	ErrPasswordTooLong            = errors.New("account: 密码长度不能超过20位")
	ErrPasswordContainsChinese    = errors.New("account: 密码不能包含中文")
	ErrPasswordContainsWhitespace = errors.New("account: 密码不能包含空格")
	ErrPasswordStrength           = errors.New("account: 密码需数字/大小写字母/字符至少3种")
	ErrEmailAlreadyExists         = errors.New("account: 该邮箱已注册")
	ErrInvalidEmailOrPassword     = errors.New("account: 邮箱或密码错误")
	ErrLoginAttemptsExceeded      = errors.New("account: 登录失败次数过多，请稍后再试")
	ErrPhoneRequired              = errors.New("account: 请输入手机号")
	ErrPhoneOrEmailRequired       = errors.New("account: 手机号或邮箱至少填写一个")
	ErrInvalidPhoneFormat         = errors.New("account: 请输入正确的手机号")
	ErrPhoneCodeRequired          = errors.New("account: 请输入验证码")
	ErrInvalidPhoneCode           = errors.New("account: 验证码错误或已过期")
	ErrPhoneCodeSendTooOften      = errors.New("account: 验证码发送太频繁，请稍后再试")
	ErrSMSDeliveryFailed          = errors.New("account: 验证码发送失败，请稍后再试")
	ErrRefreshTokenRequired       = errors.New("account: 刷新令牌不能为空")
	ErrRefreshTokenInvalid        = errors.New("account: 登录已过期，请重新登录")
	ErrUserNotFound               = errors.New("account: 用户不存在")
	ErrUserOrgNotFound            = errors.New("account: 用户组织信息不存在")
	ErrUserOrgNotAllowed          = errors.New("account: 用户未加入该组织")
	ErrLoginRequired              = errors.New("account: 请先登录")
	ErrOrgNotFound                = errors.New("account: 组织不存在")
	ErrOrgIDRequired              = errors.New("account: 组织ID不能为空")
	ErrNeedCreateCompany          = errors.New("account: 请先创建或加入组织")
	ErrJWTSecretRequired          = errors.New("account: 登录配置缺失")
	ErrOrganizationLimitExceeded  = errors.New("account: 最多只能加入三个组织")
	ErrPermissionDenied           = errors.New("account: 无权操作")

	ErrWorkerBootstrapTokenInvalid = errors.New("account: invalid worker bootstrap token")
	ErrWorkerNotFound              = errors.New("account: worker not found")
	ErrWorkerOrgMismatch           = errors.New("account: worker organization mismatch")
	ErrWorkerNotActive             = errors.New("account: worker is not active")

	ErrInvalidArg            = errors.New("account: invalid argument")
	ErrNotImplementedEdition = errors.New("account: 当前版本不支持此特性")
)
