{{- if .Values.imagePullSecret.enabled -}}
{{- if not .Values.imagePullSecret.username -}}
{{- fail "imagePullSecret.enabled=true 时必须设置 imagePullSecret.username" -}}
{{- end -}}
{{- if not .Values.imagePullSecret.password -}}
{{- fail "imagePullSecret.enabled=true 时必须设置 imagePullSecret.password" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "leros.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecret.registry .Values.imagePullSecret.username .Values.imagePullSecret.password (printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc) | b64enc | quote }}
{{- end -}}
