{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.server.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "leros.fullname" . }}-server
  labels:
    {{- include "leros.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.ingress.server.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "leros.ingressClassName" . | quote }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.server.host }}
    - host: {{ .Values.ingress.server.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.server.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "leros.serverServiceName" $ }}
                port:
                  number: {{ $.Values.server.service.port }}
          {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range .Values.ingress.server.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "leros.serverServiceName" $ }}
                port:
                  number: {{ $.Values.server.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if and .Values.web.enabled .Values.ingress.web.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "leros.fullname" . }}-web
  labels:
    {{- include "leros.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "leros.ingressClassName" . | quote }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.web.host }}
    - host: {{ .Values.ingress.web.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "leros.fullname" $ }}-web
                port:
                  number: {{ .Values.web.service.port }}
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "leros.fullname" $ }}-web
                port:
                  number: {{ .Values.web.service.port }}
    {{- end }}
{{- end }}
{{ if and .Values.account.enabled .Values.ingress.account.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "leros.accountName" (dict "root" . "type" "deployment") }}
  labels:
    {{- include "leros.labels" . | nindent 4 }}
    app.kubernetes.io/component: account
  {{- with .Values.ingress.account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "leros.ingressClassName" . | quote }}
  {{- with .Values.ingress.account.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.account.host }}
    - host: {{ .Values.ingress.account.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.account.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "leros.accountName" (dict "root" $ "type" "service") }}
                port:
                  number: {{ $.Values.account.service.port }}
          {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range .Values.ingress.account.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "leros.accountName" (dict "root" $ "type" "service") }}
                port:
                  number: {{ $.Values.account.service.port }}
          {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
